import base64
import hashlib
import re
from datetime import date


def _extract_text(content_base64: str) -> str:
    try:
        raw = base64.b64decode(content_base64)
    except Exception:  # noqa: BLE001
        return ""

    # Works for txt/csv and gives a weak fallback for binary formats.
    return raw.decode("utf-8", errors="ignore")[:8000]


def _extract_total(text: str) -> float | None:
    patterns = [
        r"(?:total|importe|monto)\s*[:=]?\s*(\d+[\.,]?\d*)",
        r"(?:s\/|pen|usd)\s*(\d+[\.,]?\d*)",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            try:
                return float(match.group(1).replace(",", "."))
            except ValueError:
                return None
    return None


def _vendor_from_text_or_filename(text: str, filename: str) -> str:
    first_line = text.strip().splitlines()[0] if text.strip() else ""
    candidate = re.sub(r"[^A-Za-z0-9\s]", " ", first_line).strip()
    if len(candidate) >= 4:
        return candidate[:80]

    clean_name = re.sub(r"[_\-.]", " ", filename).strip()
    clean_name = re.sub(r"\s+", " ", clean_name)
    return clean_name[:80] or "Proveedor Demo"


def analyze_mock(filename: str, mime_type: str, content_base64: str, text_hint: str | None) -> dict:
    text_blob = f"{text_hint or ''}\n{_extract_text(content_base64)}".strip()
    total = _extract_total(text_blob)

    fingerprint = hashlib.sha256(f"{filename}:{mime_type}:{text_blob[:300]}".encode("utf-8")).hexdigest()
    if total is None:
        total = (int(fingerprint[:6], 16) % 5000) / 10 + 20

    tax = round(total * 0.18, 2)
    subtotal = round(total - tax, 2)
    vendor = _vendor_from_text_or_filename(text_blob, filename)
    receipt_number = f"R-{fingerprint[:4].upper()}-{fingerprint[4:10].upper()}"

    confidence = 0.93 if text_hint else 0.82

    return {
        "status": "ok",
        "provider": "mock-agent",
        "model": "mock-rules-v1",
        "receipt": {
            "vendor_name": vendor,
            "vendor_tax_id": f"20{fingerprint[10:18]}",
            "receipt_number": receipt_number,
            "issue_date": date.today().isoformat(),
            "currency": "PEN",
            "subtotal": subtotal,
            "tax": tax,
            "total": round(total, 2),
            "payment_method": "CARD",
            "confidence": confidence,
            "raw_text": text_blob[:3000],
            "items": [
                {
                    "description": "Item extraido por mock",
                    "quantity": 1,
                    "unit_price": round(total, 2),
                    "line_total": round(total, 2),
                }
            ],
        },
        "warnings": ["Extraction generated by mock analyzer"],
    }
